---
name: Ansible Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set up Python 3.12 (avoid 3.14 incompatibility)
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # Install latest compatible versions of ansible and ansible-lint
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.15,<2.20"
          pip install ansible-lint

      # Run Ansible Lint
      - name: Run ansible-lint
        run: ansible-lint